PYT-45: todolist contract
abhishekrapid/learning-blockchain-hardhat pull request #1
Opened 2023-01-06 10:03 UTC by abhishekrapid

Please review the code.

2023-01-06 10:07 UTC, apoorv-nag requested changes

2023-01-06 10:07 UTC, apoorv-nag commented on hardhat.config.js
> +const ALCHEMY_API_KEY = "KEY";
take key from env file using nodejs @abhishekrapid

2023-01-06 10:07 UTC, apoorv-nag commented on hardhat.config.js
> +const GOERLI_PRIVATE_KEY = "YOUR GOERLI PRIVATE KEY";
take key from env file using nodejs @abhishekrapid

2023-01-06 10:07 UTC, apoorv-nag commented on contracts/todolist.sol
> +        require(taskId_ <= _listOfTodos.length, "Tasks are less");
use custom error which is a new feature of solidity 0.8 @abhishekrapid

2023-01-06 10:07 UTC, apoorv-nag commented on contracts/todolist.sol
> +        return _listOfTodos[taskId_].title;
check if id do not exist @abhishekrapid

2023-01-06 10:07 UTC, apoorv-nag commented on contracts/todolist.sol
> +        return _listOfTodos[taskId_].status;
check if id do not exist @abhishekrapid

2023-01-06 10:46 UTC, abhishekrapid commented on hardhat.config.js
> +const ALCHEMY_API_KEY = "KEY";
Done

2023-01-06 10:46 UTC, abhishekrapid commented on hardhat.config.js
> +const GOERLI_PRIVATE_KEY = "YOUR GOERLI PRIVATE KEY";
Done

2023-01-06 10:46 UTC, abhishekrapid commented on contracts/todolist.sol
> +        require(taskId_ <= _listOfTodos.length, "Tasks are less");
Done

2023-01-06 10:46 UTC, abhishekrapid commented on contracts/todolist.sol
> +        return _listOfTodos[taskId_].title;
Done

2023-01-23 11:41 UTC, apoorv-nag requested changes

2023-01-23 11:41 UTC, apoorv-nag commented on contracts/todolist.sol
> +pragma solidity ^0.8.4;  // Specifies the version of solidity that our code is written with
Solidity version not matching wtih hardhat config.

2023-01-23 11:41 UTC, apoorv-nag commented
@abhishekrapid please fill
<!--- Provide a general summary of your changes in the Title above -->

**Description**
<!--- Describe your changes in detail -->

**Related Issue**
<!--- This project only accepts pull requests related to open issues -->
<!--- If suggesting a new feature or change, please discuss it in an issue first -->
<!--- If fixing a bug, there should be an issue describing it with steps to reproduce -->
<!--- Please link to the issue here: -->

**Motivation and Context**
<!--- Why is this change required? What problem does it solve? -->

**How Has This Been Tested?**
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, and the tests you ran to -->
<!--- see how your change affects other areas of the code, etc. -->

**Screenshots (if appropriate):**

**Types of changes**
<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-07-18 16:24 UTC, merged